<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/08/22 15:10:15

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=selfpublish;unix_socket=/tmp/mysql.sock',
  'username' => 'root',
  'password' => 'root',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
