<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/08/20 22:45:24
sfConfig::add(array(
  'app_gravatar_default_size' => 80,
  'app_gravatar_default_rating' => 'G',
  'app_gravatar_default_image' => 'gravatar_default.png',
  'app_gravatar_cache_dir_name' => 'g_cache',
  'app_gravatar_cache_expiration' => '3 days',
  'app_sfPropelActAsCommentableBehaviorPlugin_allowed_tags' => array (
  'a' => '<a>',
  'blockquote' => '<blockquote>',
  'code' => '<code>',
  'em' => '<em>',
  'i' => '<i>',
  'p' => '<p>',
  'strong' => '<strong>',
),
  'app_sfPropelActAsCommentableBehaviorPlugin_anonymous' => array (
  'enabled' => true,
  'layout' => 
  array (
    'name' => 'required',
    'email' => 'required',
    'website' => 'optional',
    'title' => 'optional',
    'text' => 'required',
  ),
  'name' => 'Anonymous User',
),
  'app_sfPropelActAsCommentableBehaviorPlugin_count' => array (
  'enabled' => true,
  'method' => 'setSfCommentCount',
  'namespace' => 'frontend',
),
  'app_sfPropelActAsCommentableBehaviorPlugin_date_format' => 'words',
  'app_sfPropelActAsCommentableBehaviorPlugin_max_tokens' => 20,
  'app_sfPropelActAsCommentableBehaviorPlugin_namespaces' => array (
  'frontend' => NULL,
  'backend' => 'administrator',
),
  'app_sfPropelActAsCommentableBehaviorPlugin_salt' => 'c0mm3nt4bl3',
  'app_sfPropelActAsCommentableBehaviorPlugin_use_css' => true,
  'app_sfPropelActAsCommentableBehaviorPlugin_use_gravatar' => true,
  'app_sfPropelActAsCommentableBehaviorPlugin_use_routes' => true,
  'app_sfPropelActAsCommentableBehaviorPlugin_user' => array (
  'enabled' => true,
  'layout' => 
  array (
    'title' => 'optional',
    'text' => 'required',
  ),
  'table' => 'sf_guard_user',
  'id' => 'id',
  'class' => 'sfGuardUser',
  'id_method' => 'getId',
  'toString' => '__toString',
  'save_name' => false,
  'toEmail' => 'getEmail',
),
  'app_general_name' => 'Publish It Yourself',
  'app_general_baseline' => 'A self-managed publication system',
  'app_sf_guard_plugin_routes_register' => false,
  'app_sf_guard_plugin_profile_class' => 'SfGuardUserProfile',
  'app_sf_guard_plugin_profile_field_name' => 'user_id',
  'app_recaptcha_public_key' => '6LdNgwQAAAAAALo8ttBSQKz114tR7mdEqyUlNm_F',
  'app_recaptcha_private_key' => '6LdNgwQAAAAAACJ1_yXhcb6Qanqbr-tVCKekBj1x',
  'app_sfXssSafePlugin_definition' => array (
  'HTML' => 
  array (
    'DefinitionID' => 'allow flash movies',
    'DefinitionRev' => 1,
  ),
  'AutoFormat' => 
  array (
    'Custom' => 'AddParam',
    'Element' => 
    array (
      'param' => 
      array (
        'type' => false,
        'contents' => 'Empty',
        'attr_includes' => false,
        'attr' => 
        array (
          'name' => 'Text',
          'value' => 'Text',
        ),
      ),
      'object' => 
      array (
        'type' => 'Inline',
        'contents' => 'Optional: param | Flow | #PCDATA',
        'attr_includes' => false,
        'attr' => 
        array (
          'type*' => 'Enum#application/x-shockwave-flash',
          'width*' => 'Pixels',
          'height*' => 'Pixels',
          'data' => 'Text',
          'bgcolor*' => 'Text',
          'quality*' => 'Text',
        ),
      ),
      'embed' => 
      array (
        'type' => 'Block',
        'contents' => 'Empty',
        'attr_includes' => false,
        'attr' => 
        array (
          'type*' => 'Enum#application/x-shockwave-flash',
          'width*' => 'Pixels',
          'height*' => 'Pixels',
          'src*' => 'URI',
          'flashvars' => 'Text',
          'allowscriptaccess' => 'Enum#never',
          'enablejsurls' => 'Enum#false',
          'enablehref' => 'Enum#false',
          'bgcolor' => 'Text',
          'align' => 'Text',
          'quality' => 'Text',
          'wmode' => 'Text',
          'pluginspage' => 'URI',
          'saveembedtags' => 'Text',
          'salign' => 'Text',
          'scale' => 'Text',
          'name' => 'Text',
        ),
      ),
    ),
  ),
),
));
