all:
  general:
    name: Self Publish
    baseline: A self-managed publication system
    
  sf_guard_plugin:
    routes_register:    false
    profile_class:      SfGuardUserProfile
    profile_field_name: user_id
    
  
  recaptcha:
    public_key:      6LdNgwQAAAAAALo8ttBSQKz114tR7mdEqyUlNm_F
    private_key:     6LdNgwQAAAAAACJ1_yXhcb6Qanqbr-tVCKekBj1x
  
  sfXssSafePlugin:
    definition:
    
      HTML:
        DefinitionID:              'allow flash movies' 
        DefinitionRev:             1

      AutoFormat:
        Custom:                    AddParam # injector : call class "HTMLPurifier_Injector_AddParam"
        Element:
          param:
            type:                  false
            contents:              Empty
            attr_includes:         false
            attr:
              'name':              Text
              'value':             Text
              
          object:
            type:                  Inline
            contents:              'Optional: param | Flow | #PCDATA'
            attr_includes:          false
            attr:
              'type*':             'Enum#application/x-shockwave-flash'
              'width*':            Pixels
              'height*':           Pixels
              'data':              Text
              'bgcolor*':          Text
              'quality*':          Text
              
          embed:
            type:                  Block
            contents:              Empty
            attr_includes:         false
            attr:
              'type*':             'Enum#application/x-shockwave-flash'
              'width*':            Pixels
              'height*':           Pixels
              'src*':              URI
              'flashvars':         Text
              'allowscriptaccess': 'Enum#never'
              'enablejsurls':      'Enum#false'
              'enablehref':        'Enum#false'
              'bgcolor':           Text
              'align':             Text
              'quality':           Text
              'wmode':             Text
              'pluginspage':       URI
              'saveembedtags':     Text
              'salign':            Text
              'scale':             Text
              'name':              Text

  sfPropelActAsCommentableBehaviorPlugin:
    allowed_tags:
      a:              <a>
      blockquote:     <blockquote>
      code:           <code>
      em:             <em>
      i:              <i>
      p:              <p>
      strong:         <strong>
    anonymous:
      enabled:        true
      layout:
        name:         required
        email:        required
        website:      optional
        title:        optional
        text:         required
      name:           Anonymous User
    count:
      enabled:        true
      method:         setSfCommentCount
      namespace:      frontend
    date_format:      words
    max_tokens:       20
    namespaces:
      frontend:       
      backend:        administrator
    salt:             c0mm3nt4bl3
    use_css:          true
    use_gravatar:     true
    use_routes:       true
    user:
      enabled:        true
      layout:
        title:        optional
        text:         required
      table:          sf_guard_user
      id:             id
      class:          sfGuardUser
      id_method:      getId
      toString:       __toString
      toEmail:        getEmail
      save_name:      false