# Article rules
article_tags:
  url:          /tags/:tag/:page
  param:        { module: article, action: tag, page: 1 }

article_top_tags:
  url:          /top/tag/:tags/:time
  param:        { moudle: article, action: topTag, page: 1, time: 24-hours }

article_vote:
  url:          /vote/:slug
  param:        { module: article, action: vote }

article_unvote:
  url:         /unvote/:slug
  param:       { module: article, action: unvote }

article_create:
  url:          /articles
  param:        { module: article, action: create }
  class:        sfRequestRoute
  requirements: { sf_method: post }
  
article_view:
  url:          /articles/:slug.:sf_format
  param:        { module: article, action: view, sf_format: html }
  class:        sfRequestRoute
  requirements: { sf_method: get, sf_format: (?:html|atom) }

article_update:
  url:          /articles/:slug
  param:        { module: article, action: update }
  class:        sfRequestRoute
  requirements: { sf_method: put }

article_top:
  url:          /top/:time/:page.:sf_format
  param:        { module: article, action: top, page: 1, time: 24-hours, sf_format: html }
  class:        sfRequestRoute
  requirements: { sf_method: get, sf_format: (?:html|atom) }

article_top_one_page:
  url:          /top/:time.:sf_format
  param:        { module: article, action: top, page: 1, time: 24-hours, sf_format: html }
  class:        sfRequestRoute
  requirements: { sf_method: get, sf_format: (?:html|atom) }

article_most_recent:
  url:          /articles/:page.:sf_format
  param:        { module: article, action: mostRecent, page: 1, sf_format: html }
  class:        sfRequestRoute
  requirements: { sf_method: get, sf_format: (?:html|atom) }

article_most_recent_one_page:
  url:          /articles.:sf_format
  param:        { module: article, action: mostRecent, page: 1, sf_format: html }
  class:        sfRequestRoute
  requirements: { sf_method: get, sf_format: (?:html|atom) }

article_new:
  url:          /new-article
  param:        { module: article, action: new }

article_edit:
  url:          /edit-article/:slug
  param:        { module: article, action: edit }
  
# sfComment rules

sf_comment_comment:
  url:          /comments
  param:        { module: sfComment, action: comment }
  class:        sfRequestRoute
  requirements: { sf_method: post }

# sfGuard rules
sf_guard_register:
  url:          /register
  param:        { module: sfGuardAuth, action: register }

sf_guard_signin:
  url:          /login
  param:        { module: sfGuardAuth, action: signin }
 
sf_guard_signout:
  url:          /logout
  param:        { module: sfGuardAuth, action: signout }
 
sf_guard_password:
  url:          /request-password
  param:        { module: sfGuardAuth, action: password }

# default rules
homepage:
  url:          /
  param:        { module: article, action: top, page: 1, time: 24-hours }

default_index:
  url:          /:module
  param:        { action: index }

default:
  url:          /:module/:action/*