default:
  is_secure: on

selectTag:
  is_secure: off

mostRecent:
  is_secure: off

mostRecentWithTags:
  is_seucre: off
  
top:
  is_secure: off

topWithTags:
  is_secure: off

new:
  is_secure: off

create:
  is_secure: off

view:
  is_secure: off