default:
  components:
    sidebar:      [article, sidebar]

mostRecentSuccess:
  components:
    sidebar:      [article, popularTags]

mostRecentWithTagsSuccess:
  components:
    sidebar:      [article, relatedTags]

topWithTagsSuccess:
  components:
    sidebar:      [article, tagsSidebar]

newSuccess:
  javascripts:    [tiny_mce/tiny_mce.js]

editSuccess:
  javascripts:    [tiny_mce/tiny_mce.js]
  
viewSuccess:
  javascripts:    [tiny_mce/tiny_mce.js]