<?php
// auto-generated by sfRoutingConfigHandler
// date: 2009/08/22 15:10:12
return array(
'article_tags' => new sfRoute('/tags/:tag/:page', array (
  'module' => 'article',
  'action' => 'tag',
  'page' => 1,
), array (
), array (
)),
'article_top_tags' => new sfRoute('/top/tag/:tags/:time', array (
  'moudle' => 'article',
  'action' => 'topTag',
  'page' => 1,
  'time' => '24-hours',
), array (
), array (
)),
'article_vote' => new sfRoute('/vote/:slug', array (
  'module' => 'article',
  'action' => 'vote',
), array (
), array (
)),
'article_unvote' => new sfRoute('/unvote/:slug', array (
  'module' => 'article',
  'action' => 'unvote',
), array (
), array (
)),
'article_create' => new sfRequestRoute('/articles', array (
  'module' => 'article',
  'action' => 'create',
), array (
  'sf_method' => 'post',
), array (
)),
'article_view' => new sfRequestRoute('/articles/:slug.:sf_format', array (
  'module' => 'article',
  'action' => 'view',
  'sf_format' => 'html',
), array (
  'sf_method' => 'get',
  'sf_format' => '(?:html|atom)',
), array (
)),
'article_update' => new sfRequestRoute('/articles/:slug', array (
  'module' => 'article',
  'action' => 'update',
), array (
  'sf_method' => 'put',
), array (
)),
'article_top' => new sfRequestRoute('/top/:time/:page.:sf_format', array (
  'module' => 'article',
  'action' => 'top',
  'page' => 1,
  'time' => '24-hours',
  'sf_format' => 'html',
), array (
  'sf_method' => 'get',
  'sf_format' => '(?:html|atom)',
), array (
)),
'article_top_one_page' => new sfRequestRoute('/top/:time.:sf_format', array (
  'module' => 'article',
  'action' => 'top',
  'page' => 1,
  'time' => '24-hours',
  'sf_format' => 'html',
), array (
  'sf_method' => 'get',
  'sf_format' => '(?:html|atom)',
), array (
)),
'article_most_recent' => new sfRequestRoute('/articles/:page.:sf_format', array (
  'module' => 'article',
  'action' => 'mostRecent',
  'page' => 1,
  'sf_format' => 'html',
), array (
  'sf_method' => 'get',
  'sf_format' => '(?:html|atom)',
), array (
)),
'article_most_recent_one_page' => new sfRequestRoute('/articles.:sf_format', array (
  'module' => 'article',
  'action' => 'mostRecent',
  'page' => 1,
  'sf_format' => 'html',
), array (
  'sf_method' => 'get',
  'sf_format' => '(?:html|atom)',
), array (
)),
'article_new' => new sfRoute('/new-article', array (
  'module' => 'article',
  'action' => 'new',
), array (
), array (
)),
'article_edit' => new sfRoute('/edit-article/:slug', array (
  'module' => 'article',
  'action' => 'edit',
), array (
), array (
)),
'sf_comment_comment' => new sfRequestRoute('/comments', array (
  'module' => 'sfComment',
  'action' => 'comment',
), array (
  'sf_method' => 'post',
), array (
)),
'sf_guard_register' => new sfRoute('/register', array (
  'module' => 'sfGuardAuth',
  'action' => 'register',
), array (
), array (
)),
'sf_guard_signin' => new sfRoute('/login', array (
  'module' => 'sfGuardAuth',
  'action' => 'signin',
), array (
), array (
)),
'sf_guard_signout' => new sfRoute('/logout', array (
  'module' => 'sfGuardAuth',
  'action' => 'signout',
), array (
), array (
)),
'sf_guard_password' => new sfRoute('/request-password', array (
  'module' => 'sfGuardAuth',
  'action' => 'password',
), array (
), array (
)),
'homepage' => new sfRoute('/', array (
  'module' => 'article',
  'action' => 'top',
  'page' => 1,
  'time' => '24-hours',
), array (
), array (
)),
'default_index' => new sfRoute('/:module', array (
  'action' => 'index',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
);
