<?php
// auto-generated by sfSecurityConfigHandler
// date: 2009/08/22 17:59:00
$this->security = array (
  'mostrecent' => 
  array (
    'is_secure' => false,
  ),
  'mostrecentwithtags' => 
  array (
    'is_seucre' => false,
  ),
  'top' => 
  array (
    'is_secure' => false,
  ),
  'topwithtags' => 
  array (
    'is_secure' => false,
  ),
  'new' => 
  array (
    'is_secure' => false,
  ),
  'create' => 
  array (
    'is_secure' => false,
  ),
  'view' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
