<?php
// auto-generated by sfSecurityConfigHandler
// date: 2009/08/20 23:38:51
$this->security = array (
  'mostrecent' => 
  array (
    'is_secure' => false,
  ),
  'top' => 
  array (
    'is_secure' => false,
  ),
  'new' => 
  array (
    'is_secure' => false,
  ),
  'create' => 
  array (
    'is_secure' => false,
  ),
  'view' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
